default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  database: exercise1_development
test:
  <<: *default
  database: exercise1_test
production:
  <<: *default
  database: exercise1_production
  username: exercise1
  password: <%= ENV['EXERCISE1_DATABASE_PASSWORD'] %>
